//! Guest kernel management for visor microVMs.
//!
//! `visor-kernel` resolves the guest kernel binary at build time and exposes
//! `kernel_path()` for the runtime to load into VM memory. The binary format
//! varies by architecture:
//!
//! - **`x86_64`**: `vmlinux-x86_64` — uncompressed ELF binary
//! - **`aarch64`**: `Image-aarch64` — ARM64 Linux Image (PE format)
//!
//! Resolution chain (handled by `build.rs`):
//! 1. `OUT_DIR` cache — already downloaded from a previous build
//! 2. `VISOR_KERNEL_PATH` env var — explicit path to a kernel binary
//! 3. Local cache at `/var/lib/visor/kernel/{filename}`
//! 4. GitLab release download (requires `GITLAB_TOKEN`)
//!
//! The kernel config uses a fragment-based system:
//! - **Fragments** (`config/fragments/{arch}/*.config`) — human-edited, ~110 lines per arch
//! - **Lockfile** (`config/visor-kernel.config`) — fully resolved (~3,200 lines),
//!   generated by `scripts/resolve-config.sh` (in this crate), checked into git

use std::path::PathBuf;

/// Returns the path to the guest kernel binary.
///
/// The kernel is resolved at build time by `build.rs` and placed in the
/// crate's `OUT_DIR`. This function returns the path baked in at compile
/// time — it is infallible because `build.rs` panics if no kernel is found.
#[must_use]
pub fn kernel_path() -> PathBuf {
    let out_dir = env!("OUT_DIR");
    PathBuf::from(out_dir).join(env!("VISOR_KERNEL_FILENAME"))
}

/// Returns the Linux version string baked into the guest kernel.
///
/// Extracted from the kernel binary at compile time (e.g.
/// `"Linux version 7.0.0-rc1 ... #1 SMP ..."`).
#[must_use]
pub fn kernel_version() -> &'static str {
    env!("VISOR_KERNEL_VERSION")
}

/// Returns the size of the guest kernel binary in bytes.
///
/// Determined at compile time from the resolved kernel binary.
#[must_use]
pub fn kernel_size() -> u64 {
    // Set by build.rs — always a valid u64 for successful builds.
    env!("VISOR_KERNEL_SIZE").parse().unwrap_or_default()
}

/// Returns the SHA-256 hash of the guest kernel binary.
///
/// Computed at compile time by `build.rs`.
#[must_use]
pub fn kernel_sha256() -> &'static str {
    env!("VISOR_KERNEL_SHA256")
}

#[cfg(test)]
#[path = "lib_test.rs"]
mod tests;
