//! Build script for visor-kernel: resolves the pre-built guest kernel.
//!
//! Resolution order:
//! 1. `VISOR_KERNEL_PATH` env var — explicit path to a kernel binary
//! 2. Workspace root — a kernel binary beside the root `Cargo.toml`
//! 3. Local cache at `/var/lib/visor/kernel/{filename}`
//! 4. `VISOR_KERNEL_URL` release download, when one is configured
//! 5. `OUT_DIR` cache from a previous build
//! 6. Build from source — public kernel sources, no credentials required
//!
//! The kernel binary varies by target architecture:
//! - **`x86_64`**: `vmlinux-x86_64` — uncompressed ELF binary
//! - **`aarch64`**: `Image-aarch64` — ARM64 Linux Image (PE format)
//!
//! The kernel config uses a fragment-based system (like Cargo.toml → Cargo.lock):
//! - **Fragments** (`config/fragments/{arch}/*.config`) — human-edited source of truth
//! - **Lockfile** (`config/visor-kernel.config`) — fully resolved, generated by
//!   `scripts/resolve-config.sh` (in this crate), checked into git for reproducibility
//!
//! To rebuild the kernel: `crates/visor-kernel/scripts/build-kernel.sh`
//! To re-resolve config after editing fragments: `crates/visor-kernel/scripts/resolve-config.sh`

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Minimum valid kernel size (must be a real binary, not an error page).
const MIN_KERNEL_SIZE: u64 = 1_000_000;

/// Base URL for prebuilt kernel downloads, overridable with `VISOR_KERNEL_URL`.
///
/// Empty by default: the kernel builds from public sources, so a stock clone
/// needs no credentials and no particular host. Point this at a release that
/// publishes `vmlinux-x86_64` / `Image-aarch64` to skip the ~15 minute compile.
const DEFAULT_RELEASE_BASE: &str = "";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=config/visor-kernel.config");
    println!("cargo:rerun-if-changed=config/fragments");
    println!("cargo:rerun-if-env-changed=VISOR_KERNEL_PATH");
    println!("cargo:rerun-if-env-changed=VISOR_KERNEL_URL");
    println!("cargo:rerun-if-env-changed=VISOR_KERNEL_NO_BUILD");
    println!("cargo:rerun-if-env-changed=GITLAB_TOKEN");

    let target_arch =
        std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "x86_64".to_owned());

    let (kernel_filename, download_path) = match target_arch.as_str() {
        "aarch64" => ("Image-aarch64", "Image-aarch64"),
        _ => ("vmlinux-x86_64", "vmlinux"),
    };

    let local_cache_path = format!("/var/lib/visor/kernel/{kernel_filename}");
    let release_base = std::env::var("VISOR_KERNEL_URL")
        .unwrap_or_else(|_| DEFAULT_RELEASE_BASE.to_owned());
    let download_url = if release_base.is_empty() {
        String::new()
    } else {
        format!("{}/{download_path}", release_base.trim_end_matches('/'))
    };

    // Emit the kernel filename so lib.rs can use it via env!()
    println!("cargo:rustc-env=VISOR_KERNEL_FILENAME={kernel_filename}");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join(kernel_filename);

    resolve_kernel(&dest, kernel_filename, &local_cache_path, &download_url);
    emit_kernel_metadata(&dest);
}

/// Resolves the kernel binary to `dest`, cheapest source first and a source
/// build as the backstop, so a stock clone needs no credentials.
fn resolve_kernel(dest: &Path, kernel_filename: &str, local_cache_path: &str, download_url: &str) {
    // 1. Explicit path via VISOR_KERNEL_PATH env var
    if let Ok(explicit_path) = std::env::var("VISOR_KERNEL_PATH") {
        let src = PathBuf::from(&explicit_path);
        if is_valid_kernel(&src) {
            copy_kernel(&src, dest);
            return;
        }
        eprintln!(
            "visor-kernel: VISOR_KERNEL_PATH={explicit_path} is not a valid kernel, trying other sources"
        );
    }

    // 2. Workspace root (dev builds — kernel binary alongside root Cargo.toml)
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let workspace_root = Path::new(&manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .unwrap_or(Path::new("."));
    let workspace_kernel = workspace_root.join(kernel_filename);
    if is_valid_kernel(&workspace_kernel) {
        eprintln!(
            "visor-kernel: using kernel from workspace root at {}",
            workspace_kernel.display()
        );
        copy_kernel(&workspace_kernel, dest);
        return;
    }

    // 3. Local cache at /var/lib/visor/kernel/
    let local_cache = Path::new(local_cache_path);
    if is_valid_kernel(local_cache) {
        eprintln!("visor-kernel: copying kernel from local cache {local_cache_path}");
        copy_kernel(local_cache, dest);
        return;
    }

    // 4. Prebuilt release, when one is configured. Authenticated only if a
    //    token happens to be present — a public asset needs none.
    if !download_url.is_empty() {
        eprintln!("visor-kernel: downloading kernel from {download_url}");
        if try_download(gitlab_token().as_deref(), download_url, dest) {
            return;
        }
        eprintln!("visor-kernel: download failed, see error above");
    }

    // 5. OUT_DIR cache from a previous build.
    if is_valid_kernel(dest) {
        eprintln!("visor-kernel: using cached kernel at {}", dest.display());
        return;
    }

    // 6. Build it. Public sources, no credentials — which is what makes a
    //    stock clone buildable. Slow enough to be worth announcing, and
    //    opt-out-able for environments that would rather fail fast.
    if std::env::var("VISOR_KERNEL_NO_BUILD").is_err() && try_build_from_source(dest) {
        return;
    }

    panic!(
        "\n\
        visor-kernel: could not obtain a kernel binary.\n\
        \n\
        Options:\n\
        1. Build from source:   ./crates/visor-kernel/scripts/build-kernel.sh\n\
        2. Set explicit path:   VISOR_KERNEL_PATH=/path/to/kernel cargo build\n\
        3. Copy to local cache: cp kernel {local_cache_path}\n\
        4. Use a release:       VISOR_KERNEL_URL=https://host/downloads cargo build\n\
        "
    );
}

/// Compile the guest kernel with the in-repo config, from public sources.
fn try_build_from_source(dest: &Path) -> bool {
    // Host, not target: the script drives a Linux kernel build with Linux
    // tooling, so anywhere else it would burn minutes only to fail.
    if !cfg!(target_os = "linux") {
        eprintln!("visor-kernel: kernel builds need a Linux host; skipping the source build");
        return false;
    }
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let script = Path::new(&manifest_dir).join("scripts/build-kernel.sh");
    if !script.is_file() {
        return false;
    }
    eprintln!(
        "visor-kernel: no prebuilt kernel found — building from source, which takes \
         roughly 15 minutes on a cold cache. Set VISOR_KERNEL_URL to use a published \
         binary instead, or VISOR_KERNEL_NO_BUILD=1 to fail rather than compile."
    );
    let status = std::process::Command::new(&script).arg(dest).status();
    match status {
        Ok(s) if s.success() && is_valid_kernel(dest) => true,
        Ok(s) => {
            eprintln!("visor-kernel: kernel build exited with {s}");
            false
        }
        Err(e) => {
            eprintln!("visor-kernel: could not run {}: {e}", script.display());
            false
        }
    }
}

fn is_valid_kernel(path: &Path) -> bool {
    match fs::metadata(path) {
        Ok(meta) => meta.len() >= MIN_KERNEL_SIZE,
        Err(_) => false,
    }
}

fn copy_kernel(src: &Path, dest: &Path) {
    fs::copy(src, dest).unwrap_or_else(|e| {
        panic!(
            "visor-kernel: failed to copy {} → {}: {e}",
            src.display(),
            dest.display()
        )
    });
    let size = fs::metadata(dest).map_or(0, |m| m.len());
    eprintln!(
        "visor-kernel: kernel ready at {} ({size} bytes)",
        dest.display(),
    );
}

fn gitlab_token() -> Option<String> {
    std::env::var("GITLAB_TOKEN")
        .ok()
        .or_else(|| std::env::var("CI_JOB_TOKEN").ok())
        .filter(|t| !t.is_empty())
}

fn try_download(token: Option<&str>, url: &str, dest: &Path) -> bool {
    let client = match reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(300))
        .build()
    {
        Ok(c) => c,
        Err(e) => {
            eprintln!("visor-kernel: failed to create HTTP client: {e}");
            return false;
        }
    };

    // A public asset needs no token; an authenticated host gets one if the
    // environment supplied it.
    let request = match token {
        Some(t) => client.get(url).header("PRIVATE-TOKEN", t),
        None => client.get(url),
    };
    let response = match request.send() {
        Ok(r) => r,
        Err(e) => {
            eprintln!("visor-kernel: download request failed: {e}");
            return false;
        }
    };

    if !response.status().is_success() {
        eprintln!(
            "visor-kernel: download returned HTTP {} — is the asset public, or is a token needed?",
            response.status()
        );
        return false;
    }

    let bytes = match response.bytes() {
        Ok(b) => b,
        Err(e) => {
            eprintln!("visor-kernel: failed to read response body: {e}");
            return false;
        }
    };

    if (bytes.len() as u64) < MIN_KERNEL_SIZE {
        eprintln!(
            "visor-kernel: downloaded {} bytes — too small, likely an error page",
            bytes.len()
        );
        return false;
    }

    let mut file = match fs::File::create(dest) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("visor-kernel: failed to create {}: {e}", dest.display());
            return false;
        }
    };

    if let Err(e) = file.write_all(&bytes) {
        eprintln!(
            "visor-kernel: failed to write kernel to {}: {e}",
            dest.display()
        );
        return false;
    }

    eprintln!(
        "visor-kernel: downloaded {} bytes to {}",
        bytes.len(),
        dest.display()
    );
    true
}

/// Emits compile-time metadata for the resolved kernel binary.
///
/// Sets `VISOR_KERNEL_VERSION`, `VISOR_KERNEL_SIZE`, and `VISOR_KERNEL_SHA256`
/// as `cargo:rustc-env` variables, accessible via `env!()` in `lib.rs`.
fn emit_kernel_metadata(path: &Path) {
    let size = fs::metadata(path).map_or(0, |m| m.len());
    println!("cargo:rustc-env=VISOR_KERNEL_SIZE={size}");

    let sha256 = compute_sha256(path);
    println!("cargo:rustc-env=VISOR_KERNEL_SHA256={sha256}");

    let version = extract_kernel_version(path);
    println!("cargo:rustc-env=VISOR_KERNEL_VERSION={version}");

    eprintln!("visor-kernel: metadata — version={version}, size={size}, sha256={sha256}");
}

/// Computes the SHA-256 hash of a file using available system tools.
///
/// Tries `sha256sum` (Linux, most BSDs) first, then falls back to
/// `shasum -a 256` (macOS). Returns `"unknown"` if neither works.
fn compute_sha256(path: &Path) -> String {
    // Try sha256sum (Linux, most BSDs)
    let output = std::process::Command::new("sha256sum").arg(path).output();
    if let Ok(ref out) = output {
        if out.status.success() {
            let stdout = String::from_utf8_lossy(&out.stdout);
            if let Some(hash) = stdout.split_whitespace().next() {
                return hash.to_owned();
            }
        }
    }

    // Fall back to shasum -a 256 (macOS)
    let output = std::process::Command::new("shasum")
        .args(["-a", "256"])
        .arg(path)
        .output();
    if let Ok(ref out) = output {
        if out.status.success() {
            let stdout = String::from_utf8_lossy(&out.stdout);
            if let Some(hash) = stdout.split_whitespace().next() {
                return hash.to_owned();
            }
        }
    }

    "unknown".to_owned()
}

/// Extracts the `Linux version ...` string from a kernel binary.
///
/// Works for both ELF (`vmlinux`) and ARM64 Image formats — both embed
/// the version string as raw bytes. Scans for the `"Linux version "` marker
/// and reads until a null byte or newline. Returns `"unknown"` if not found.
fn extract_kernel_version(path: &Path) -> String {
    let Ok(data) = fs::read(path) else {
        return "unknown".to_owned();
    };
    let needle = b"Linux version ";
    if let Some(pos) = data.windows(needle.len()).position(|w| w == needle) {
        let max_end = (pos + 256).min(data.len());
        let end = data[pos..max_end]
            .iter()
            .position(|&b| b == 0 || b == 0x0A)
            .map_or(max_end, |n| pos + n);
        String::from_utf8_lossy(&data[pos..end]).into_owned()
    } else {
        "unknown".to_owned()
    }
}
